# Generated by Django 4.1.7 on 2023-03-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titile',
            new_name='title',
        ),
    ]
